//! Translated from `src/nvim/option_vars.h`, plus the option-specific
//! bit-flag enums and string-value-set arrays from
//! `option_vars.generated.h` (generated by `src/gen/gen_options.lua`
//! from `src/options.lua`'s master option table - translated directly
//! from a pre-built copy of that generated file found in this
//! checkout's own `build/src/nvim/auto/option_vars.generated.h`,
//! matching this project's "translate the generator's output directly"
//! convention for codegen-derived content, same as how
//! `ex_cmds_defs.rs`'s deferred `cmdidx_T` will eventually be handled).
//!
//! Translated: every one of the header's 337 `EXTERN`/`extern` global
//! option-value variables (as a single [`OptionVars`] struct, mirroring
//! `globals.rs`'s own `Globals` struct for the exact same "one flat
//! process-wide mutable state bag, reachable from any function with no
//! parameter" reason - see that file's module doc comment), the 20
//! option-specific bit-flag enums (as `pub mod` bit-flag constant groups,
//! matching `HL_*`/`MarkMoveRes` elsewhere in this crate, since they
//! combine via bitwise OR rather than being mutually exclusive
//! variants), the ~45 `opt_*_values` valid-string-value arrays, and the
//! smaller standalone character/string constant groups (`CPO_*`, `WW_*`,
//! `MOUSE_*`, `SHM_*`, `GO_*`, `COM_*`, `BS_*`, etc.).
//!
//! `empty_string_option` is translated as a plain constant (not an
//! `OptionVars` field): its only purpose in the original is "a non-NULL
//! sentinel so `char *` option fields never need a NULL check" - this
//! crate already represents nullable string options as `Option<Vec<u8>>`
//! throughout, which makes that sentinel trick structurally unnecessary,
//! but the constant is kept for direct traceability back to the source.

use crate::sign_defs::SIGN_SHOW_MAX;
use crate::types_defs::{OptInt, SIGN_WIDTH};

// ============================================================
// Small standalone character/string constant groups.
// ============================================================

/// `'highlight'` default value (`HIGHLIGHT_INIT`).
pub const HIGHLIGHT_INIT: &str = "8:SpecialKey,~:EndOfBuffer,z:TermCursor,@:NonText,d:Directory,e:ErrorMsg,i:IncSearch,l:Search,y:CurSearch,m:MoreMsg,M:ModeMsg,n:LineNr,a:LineNrAbove,b:LineNrBelow,N:CursorLineNr,G:CursorLineSign,O:CursorLineFold,r:Question,s:StatusLine,S:StatusLineNC,c:VertSplit,t:Title,v:Visual,V:VisualNOS,w:WarningMsg,W:WildMenu,f:Folded,F:FoldColumn,A:DiffAdd,C:DiffChange,D:DiffDelete,T:DiffText,E:DiffTextAdd,>:SignColumn,-:Conceal,B:SpellBad,P:SpellCap,R:SpellRare,L:SpellLocal,+:Pmenu,=:PmenuSel,k:PmenuMatch,<:PmenuMatchSel,[:PmenuKind,]:PmenuKindSel,{:PmenuExtra,}:PmenuExtraSel,x:PmenuSbar,X:PmenuThumb,*:TabLine,#:TabLineSel,_:TabLineFill,!:CursorColumn,.:CursorLine,o:ColorColumn,q:QuickFixLine,z:StatusLineTerm,Z:StatusLineTermNC,g:MsgArea,h:ComplMatchIns,0:Whitespace,I:PreInsert";

/// Default value for `'errorformat'` on non-Windows (`DFLT_EFM`). The
/// Windows variant is functionally equivalent but with different path
/// patterns; only the non-Windows default is translated here since
/// `#ifdef MSWIN`'s choice is a build-time constant this crate doesn't
/// yet have a matching cfg-gated *value* mechanism for beyond simple
/// bools (see `os/win_defs.rs`'s `BACKSLASH_IN_FILENAME` precedent for
/// the bool case) - deferred until `option.c` itself needs to pick one
/// at startup.
pub const DFLT_EFM: &str = "%*[^\"]\"%f\"%*\\D%l: %m,\"%f\"%*\\D%l: %m,%-Gg%\\?make[%*\\d]: *** [%f:%l:%m,%-Gg%\\?make: *** [%f:%l:%m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file included from %f:%l:%c:,%-GIn file included from %f:%l:%c\\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[ ]from %f:%l\\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,\"%f\"\\, line %l%*\\D%c%*[^ ] %m,%D%*\\a[%*\\d]: Entering directory %*[`']%f',%X%*\\a[%*\\d]: Leaving directory %*[`']%f',%D%*\\a: Entering directory %*[`']%f',%X%*\\a: Leaving directory %*[`']%f',%DMaking %*\\a in %f,%f|%l| %m";

/// Default value for `'guifont'` (`DFLT_GFN`), non-Windows/non-macOS
/// (Linux) variant - see [`DFLT_EFM`]'s note on platform-specific
/// defaults.
pub const DFLT_GFN: &str = "DejaVu Sans Mono,Courier New,monospace";

pub const DFLT_GREPFORMAT: &str = "%f:%l:%m,%f:%l%m,%f  %l%m";

/// check for BOM at start of file (`ENC_UCSBOM`).
pub const ENC_UCSBOM: &str = "ucs-bom";
/// default value for `'encoding'` (`ENC_DFLT`).
pub const ENC_DFLT: &str = "utf-8";

// End-of-line style.
pub const EOL_UNKNOWN: i32 = -1;
pub const EOL_UNIX: i32 = 0;
pub const EOL_DOS: i32 = 1;
pub const EOL_MAC: i32 = 2;

// Formatting options for p_fo 'formatoptions'.
pub const FO_WRAP: u8 = b't';
pub const FO_WRAP_COMS: u8 = b'c';
pub const FO_RET_COMS: u8 = b'r';
pub const FO_OPEN_COMS: u8 = b'o';
pub const FO_NO_OPEN_COMS: u8 = b'/';
pub const FO_Q_COMS: u8 = b'q';
pub const FO_Q_NUMBER: u8 = b'n';
pub const FO_Q_SECOND: u8 = b'2';
pub const FO_INS_VI: u8 = b'v';
pub const FO_INS_LONG: u8 = b'l';
pub const FO_INS_BLANK: u8 = b'b';
/// break before/after multi-byte char
pub const FO_MBYTE_BREAK: u8 = b'm';
/// no space before/after multi-byte char
pub const FO_MBYTE_JOIN: u8 = b'M';
/// no space between multi-byte chars
pub const FO_MBYTE_JOIN2: u8 = b'B';
pub const FO_ONE_LETTER: u8 = b'1';
/// trailing white space continues paragr.
pub const FO_WHITE_PAR: u8 = b'w';
/// automatic formatting
pub const FO_AUTO: u8 = b'a';
/// respect textwidth rigorously
pub const FO_RIGOROUS_TW: u8 = b']';
/// remove comment leaders when joining lines
pub const FO_REMOVE_COMS: u8 = b'j';
/// don't break a single space after a period
pub const FO_PERIOD_ABBR: u8 = b'p';

pub const DFLT_FO_VI: &str = "vt";
pub const DFLT_FO_VIM: &str = "tcqj";
/// for `do_set()`
pub const FO_ALL: &str = "tcro/q2vlb1mMBn,aw]jp";

/// fixed value for `'maxcombine'`
pub const MAX_MCO: i32 = 6;

// Characters for the p_cpo option.
pub const CPO_ALTREAD: u8 = b'a';
pub const CPO_ALTWRITE: u8 = b'A';
pub const CPO_BAR: u8 = b'b';
pub const CPO_BSLASH: u8 = b'B';
pub const CPO_SEARCH: u8 = b'c';
pub const CPO_CONCAT: u8 = b'C';
pub const CPO_DOTTAG: u8 = b'd';
pub const CPO_DIGRAPH: u8 = b'D';
pub const CPO_EXECBUF: u8 = b'e';
pub const CPO_EMPTYREGION: u8 = b'E';
pub const CPO_FNAMER: u8 = b'f';
pub const CPO_FNAMEW: u8 = b'F';
pub const CPO_INTMOD: u8 = b'i';
pub const CPO_INDENT: u8 = b'I';
pub const CPO_ENDOFSENT: u8 = b'J';
pub const CPO_KOFFSET: u8 = b'K';
pub const CPO_LITERAL: u8 = b'l';
pub const CPO_LISTWM: u8 = b'L';
pub const CPO_SHOWMATCH: u8 = b'm';
pub const CPO_MATCHBSL: u8 = b'M';
pub const CPO_NUMCOL: u8 = b'n';
pub const CPO_LINEOFF: u8 = b'o';
pub const CPO_OVERNEW: u8 = b'O';
pub const CPO_FNAMEAPP: u8 = b'P';
pub const CPO_JOINCOL: u8 = b'q';
pub const CPO_REDO: u8 = b'r';
pub const CPO_REMMARK: u8 = b'R';
pub const CPO_BUFOPT: u8 = b's';
pub const CPO_BUFOPTGLOB: u8 = b'S';
pub const CPO_TAGPAT: u8 = b't';
pub const CPO_UNDO: u8 = b'u';
pub const CPO_BACKSPACE: u8 = b'v';
pub const CPO_FWRITE: u8 = b'W';
pub const CPO_ESC: u8 = b'x';
pub const CPO_REPLCNT: u8 = b'X';
pub const CPO_YANK: u8 = b'y';
pub const CPO_KEEPRO: u8 = b'Z';
pub const CPO_DOLLAR: u8 = b'$';
pub const CPO_FILTER: u8 = b'!';
pub const CPO_MATCH: u8 = b'%';
pub const CPO_PLUS: u8 = b'+';
pub const CPO_REGAPPEND: u8 = b'>';
pub const CPO_SCOLON: u8 = b';';
pub const CPO_NOSYMLINKS: u8 = b'~';
pub const CPO_CHANGEW: u8 = b'_';
/// default values for Vim and Vi
pub const CPO_VIM: &str = "aABceFs_";
pub const CPO_VI: &str = "aAbBcCdDeEfFiIJKlLmMnoOpPqrRsStuvWxXyZ$!%+>;~_";

/// characters for p_ww option
pub const WW_ALL: &str = "bshl<>[]~";

// Characters for the p_mouse option.
/// use mouse in Normal mode
pub const MOUSE_NORMAL: u8 = b'n';
/// use mouse in Visual/Select mode
pub const MOUSE_VISUAL: u8 = b'v';
/// use mouse in Insert mode
pub const MOUSE_INSERT: u8 = b'i';
/// use mouse in Command-line mode
pub const MOUSE_COMMAND: u8 = b'c';
/// use mouse in help buffers
pub const MOUSE_HELP: u8 = b'h';
/// use mouse for hit-return message
pub const MOUSE_RETURN: u8 = b'r';
/// used for 'a' flag
pub const MOUSE_A: &str = "nvich";
/// all possible characters
pub const MOUSE_ALL: &str = "anvichr";
/// don't use Visual selection
pub const MOUSE_NONE: u8 = b' ';
/// forced modeless selection
pub const MOUSE_NONEF: u8 = b'x';

// Default vertical and horizontal mouse scroll values. Note: This
// should be in sync with the default mousescroll option.
pub const MOUSESCROLL_VERT_DFLT: OptInt = 3;
pub const MOUSESCROLL_HOR_DFLT: OptInt = 6;

/// flags for `'concealcursor'`
pub const COCU_ALL: &str = "nvic";

/// characters for p_shm option (`SHM_*`).
pub mod shm {
    /// Readonly.
    pub const RO: u8 = b'r';
    /// Modified.
    pub const MOD: u8 = b'm';
    /// "L" instead of "lines".
    pub const LINES: u8 = b'l';
    /// "\[w\]" instead of "written".
    pub const WRI: u8 = b'w';
    /// Use abbreviations from `SHM_ALL_ABBREVIATIONS`.
    pub const ABBREVIATIONS: u8 = b'a';
    /// Don't use "written" at all.
    pub const WRITE: u8 = b'W';
    /// Truncate file messages.
    pub const TRUNC: u8 = b't';
    /// Truncate all messages.
    pub const TRUNCALL: u8 = b'T';
    /// Overwrite file messages.
    pub const OVER: u8 = b'o';
    /// Overwrite more messages.
    pub const OVERALL: u8 = b'O';
    /// No search hit bottom messages.
    pub const SEARCH: u8 = b's';
    /// No ATTENTION messages.
    pub const ATTENTION: u8 = b'A';
    /// Intro messages.
    pub const INTRO: u8 = b'I';
    /// Completion menu messages.
    pub const COMPLETIONMENU: u8 = b'c';
    /// Completion scanning messages.
    pub const COMPLETIONSCAN: u8 = b'C';
    /// No recording message.
    pub const RECORDING: u8 = b'q';
    /// No file info messages.
    pub const FILEINFO: u8 = b'F';
    /// No search stats: '[1/10]'.
    pub const SEARCHCOUNT: u8 = b'S';
    /// No undo messages.
    pub const UNDO: u8 = b'u';
}

/// Represented by 'a' flag (`SHM_ALL_ABBREVIATIONS`).
pub const SHM_ALL_ABBREVIATIONS: [u8; 4] = [shm::RO, shm::MOD, shm::LINES, shm::WRI];

// Characters for p_go (kept for completeness/traceability even though
// this crate has no GUI - see the original's own comment: these are all
// GUI-only flags).
pub const GO_ASEL: u8 = b'a';
pub const GO_ASELML: u8 = b'A';
pub const GO_BOT: u8 = b'b';
pub const GO_CONDIALOG: u8 = b'c';
pub const GO_TITLEBAR: u8 = b'C';
pub const GO_DARKTHEME: u8 = b'd';
pub const GO_TABLINE: u8 = b'e';
pub const GO_FORG: u8 = b'f';
pub const GO_GREY: u8 = b'g';
pub const GO_HORSCROLL: u8 = b'h';
pub const GO_ICON: u8 = b'i';
pub const GO_LEFT: u8 = b'l';
pub const GO_VLEFT: u8 = b'L';
pub const GO_MENUS: u8 = b'm';
pub const GO_NOSYSMENU: u8 = b'M';
pub const GO_POINTER: u8 = b'p';
pub const GO_ASELPLUS: u8 = b'P';
pub const GO_RIGHT: u8 = b'r';
pub const GO_VRIGHT: u8 = b'R';
pub const GO_TOOLBAR: u8 = b'T';
pub const GO_FOOTER: u8 = b'F';
pub const GO_VERTICAL: u8 = b'v';
pub const GO_KEEPWINSIZE: u8 = b'k';
/// all possible flags for 'go'
pub const GO_ALL: &str = "!aAbcCdefFghilLmMpPrRtTvk";

// Flags for 'comments' option.
/// comments strings nest
pub const COM_NEST: u8 = b'n';
/// needs blank after string
pub const COM_BLANK: u8 = b'b';
/// start of comment
pub const COM_START: u8 = b's';
/// middle of comment
pub const COM_MIDDLE: u8 = b'm';
/// end of comment
pub const COM_END: u8 = b'e';
/// last char of end closes comment
pub const COM_AUTO_END: u8 = b'x';
/// first line comment only
pub const COM_FIRST: u8 = b'f';
/// left adjusted
pub const COM_LEFT: u8 = b'l';
/// right adjusted
pub const COM_RIGHT: u8 = b'r';
/// don't use for "O" command
pub const COM_NOBACK: u8 = b'O';
/// all flags for 'comments' option
pub const COM_ALL: &str = "nbsmexflrO";
/// maximum length of a part
pub const COM_MAX_LEN: i32 = 50;

// Arguments for can_bs() (not yet translated). Each defined char should
// be unique over all values except for BS_START, that intentionally
// also matches BS_NOSTOP because BS_NOSTOP behaves exactly the same
// except it does not stop at the start of the insert point.
pub const BS_INDENT: u8 = b'i';
pub const BS_EOL: u8 = b'l';
pub const BS_START: u8 = b's';
pub const BS_NOSTOP: u8 = b'p';

pub const LISPWORD_VALUE: &str = "defun,define,defmacro,set!,lambda,if,case,let,flet,let*,letrec,do,do*,define-syntax,let-syntax,letrec-syntax,destructuring-bind,defpackage,defparameter,defstruct,deftype,defvar,do-all-symbols,do-external-symbols,do-symbols,dolist,dotimes,ecase,etypecase,eval-when,labels,macrolet,multiple-value-bind,multiple-value-call,multiple-value-prog1,multiple-value-setq,prog1,progv,typecase,unless,unwind-protect,when,with-input-from-string,with-open-file,with-open-stream,with-output-to-string,with-package-iterator,define-condition,handler-bind,handler-case,restart-bind,restart-case,with-simple-restart,store-value,use-value,muffle-warning,abort,continue,with-slots,with-slots*,with-accessors,with-accessors*,defclass,defmethod,print-unreadable-object";

// When a string option is NULL, it is set to empty_string_option, to
// avoid having to check for NULL everywhere - see this module's own doc
// comment on why this crate doesn't need the equivalent.
pub const EMPTY_STRING_OPTION: &[u8] = b"";

/// Value for `b_p_ul` indicating the global value must be used
/// (`NO_LOCAL_UNDOLEVEL`).
pub const NO_LOCAL_UNDOLEVEL: OptInt = -123_456;

pub const ERR_BUFLEN: usize = 80;

/// Maximum `'scrollback'` value (`SB_MAX`).
pub const SB_MAX: i32 = 1_000_000;

/// used for `'numberwidth'` (`MAX_NUMBERWIDTH`).
pub const MAX_NUMBERWIDTH: i32 = 20;

/// Maximum `'statuscolumn'` width: number + sign + fold columns
/// (`MAX_STCWIDTH`).
pub const MAX_STCWIDTH: i32 = MAX_NUMBERWIDTH + SIGN_SHOW_MAX * SIGN_WIDTH + 9;

pub const TABSTOP_MAX: i32 = 9999;

/// `'signcolumn'` set to "no" (`SCL_NO`).
pub const SCL_NO: i32 = -1;
/// `'signcolumn'` set to "number" (`SCL_NUM`).
pub const SCL_NUM: i32 = -2;

// ============================================================
// Option-specific bit-flag enums (option_vars.generated.h).
// Kept as plain `u32` bit-flag constant groups (`pub mod`), matching
// `HL_*`/`MarkMoveRes` elsewhere in this crate, since they combine via
// bitwise OR (stored in each option's own `*_flags: u32` field) rather
// than being mutually exclusive variants.
// ============================================================

/// flags from `'backupcopy'` (`OptBkcFlags`).
pub mod opt_bkc_flag {
    pub const YES: u32 = 0x01;
    pub const AUTO: u32 = 0x02;
    pub const NO: u32 = 0x04;
    pub const BREAKSYMLINK: u32 = 0x08;
    pub const BREAKHARDLINK: u32 = 0x10;
}

/// flags from `'belloff'` (`OptBoFlags`).
pub mod opt_bo_flag {
    pub const ALL: u32 = 0x01;
    pub const BACKSPACE: u32 = 0x02;
    pub const CURSOR: u32 = 0x04;
    pub const COMPLETE: u32 = 0x08;
    pub const COPY: u32 = 0x10;
    pub const CTRLG: u32 = 0x20;
    pub const ERROR: u32 = 0x40;
    pub const ESC: u32 = 0x80;
    pub const EX: u32 = 0x100;
    pub const HANGUL: u32 = 0x200;
    pub const INSERTMODE: u32 = 0x400;
    pub const LANG: u32 = 0x800;
    pub const MESS: u32 = 0x1000;
    pub const SHOWMATCH: u32 = 0x2000;
    pub const OPERATOR: u32 = 0x4000;
    pub const REGISTER: u32 = 0x8000;
    pub const SHELL: u32 = 0x10000;
    pub const SPELL: u32 = 0x20000;
    pub const TERM: u32 = 0x40000;
    pub const WILDMODE: u32 = 0x80000;
}

/// flags from `'casemap'` (`OptCmpFlags`).
pub mod opt_cmp_flag {
    pub const INTERNAL: u32 = 0x01;
    pub const KEEPASCII: u32 = 0x02;
}

/// flags from `'clipboard'` (`OptCbFlags`).
pub mod opt_cb_flag {
    pub const UNNAMED: u32 = 0x01;
    pub const UNNAMEDPLUS: u32 = 0x02;
}

/// flags from `'completeopt'` (`OptCotFlags`).
pub mod opt_cot_flag {
    pub const FUZZY: u32 = 0x01;
    pub const LONGEST: u32 = 0x02;
    pub const MENU: u32 = 0x04;
    pub const MENUONE: u32 = 0x08;
    pub const NEAREST: u32 = 0x10;
    pub const NOINSERT: u32 = 0x20;
    pub const NOSELECT: u32 = 0x40;
    pub const NOSORT: u32 = 0x80;
    pub const POPUP: u32 = 0x100;
    pub const PREINSERT: u32 = 0x200;
    pub const PRESELECT: u32 = 0x400;
    pub const PREVIEW: u32 = 0x800;
}

/// flags for cursorline highlighting, from `'culopt'` (`OptCuloptFlags`).
pub mod opt_culopt_flag {
    pub const LINE: u32 = 0x01;
    pub const SCREENLINE: u32 = 0x02;
    pub const NUMBER: u32 = 0x04;
}

/// flags from `'display'` (`OptDyFlags`).
pub mod opt_dy_flag {
    pub const LASTLINE: u32 = 0x01;
    pub const TRUNCATE: u32 = 0x02;
    pub const UHEX: u32 = 0x04;
    pub const MSGSEP: u32 = 0x08;
}

/// flags from `'foldopen'` (`OptFdoFlags`).
pub mod opt_fdo_flag {
    pub const ALL: u32 = 0x01;
    pub const BLOCK: u32 = 0x02;
    pub const HOR: u32 = 0x04;
    pub const MARK: u32 = 0x08;
    pub const PERCENT: u32 = 0x10;
    pub const QUICKFIX: u32 = 0x20;
    pub const SEARCH: u32 = 0x40;
    pub const TAG: u32 = 0x80;
    pub const INSERT: u32 = 0x100;
    pub const UNDO: u32 = 0x200;
    pub const JUMP: u32 = 0x400;
}

/// flags from `'jumpoptions'` (`OptJopFlags`).
pub mod opt_jop_flag {
    pub const STACK: u32 = 0x01;
    pub const VIEW: u32 = 0x02;
    pub const CLEAN: u32 = 0x04;
}

/// flags from `'messagesopt'` (`OptMoptFlags`).
pub mod opt_mopt_flag {
    pub const HIT_ENTER: u32 = 0x01;
    pub const WAIT: u32 = 0x02;
    pub const HISTORY: u32 = 0x04;
    pub const PROGRESS: u32 = 0x08;
}

/// flags from `'redrawdebug'` (`OptRdbFlags`).
pub mod opt_rdb_flag {
    pub const COMPOSITOR: u32 = 0x01;
    pub const NOTHROTTLE: u32 = 0x02;
    pub const INVALID: u32 = 0x04;
    pub const NODELTA: u32 = 0x08;
    pub const LINE: u32 = 0x10;
    pub const FLUSH: u32 = 0x20;
}

/// flags from `'sessionoptions'` (and `'viewoptions'`, which "uses
/// OptSsopFlags" per the original's own comment on `vop_flags`)
/// (`OptSsopFlags`).
pub mod opt_ssop_flag {
    pub const BUFFERS: u32 = 0x01;
    pub const WINPOS: u32 = 0x02;
    pub const RESIZE: u32 = 0x04;
    pub const WINSIZE: u32 = 0x08;
    pub const LOCALOPTIONS: u32 = 0x10;
    pub const OPTIONS: u32 = 0x20;
    pub const HELP: u32 = 0x40;
    pub const BLANK: u32 = 0x80;
    pub const GLOBALS: u32 = 0x100;
    pub const SLASH: u32 = 0x200;
    pub const UNIX: u32 = 0x400;
    pub const SESDIR: u32 = 0x800;
    pub const CURDIR: u32 = 0x1000;
    pub const FOLDS: u32 = 0x2000;
    pub const CURSOR: u32 = 0x4000;
    pub const TABPAGES: u32 = 0x8000;
    pub const TERMINAL: u32 = 0x10000;
    pub const SKIPRTP: u32 = 0x20000;
}

/// flags from `'spelloptions'` (`OptSpoFlags`).
pub mod opt_spo_flag {
    pub const CAMEL: u32 = 0x01;
    pub const NOPLAINBUFFER: u32 = 0x02;
}

/// flags from `'switchbuf'` (`OptSwbFlags`).
pub mod opt_swb_flag {
    pub const USEOPEN: u32 = 0x01;
    pub const USETAB: u32 = 0x02;
    pub const SPLIT: u32 = 0x04;
    pub const NEWTAB: u32 = 0x08;
    pub const VSPLIT: u32 = 0x10;
    pub const USELAST: u32 = 0x20;
}

/// flags from `'tabclose'` (`OptTclFlags`).
pub mod opt_tcl_flag {
    pub const LEFT: u32 = 0x01;
    pub const USELAST: u32 = 0x02;
}

/// flags from `'tagcase'` (`OptTcFlags`).
pub mod opt_tc_flag {
    pub const FOLLOWIC: u32 = 0x01;
    pub const IGNORE: u32 = 0x02;
    pub const MATCH: u32 = 0x04;
    pub const FOLLOWSCS: u32 = 0x08;
    pub const SMART: u32 = 0x10;
}

/// flags from `'termpastefilter'` (`OptTpfFlags`).
pub mod opt_tpf_flag {
    pub const BS: u32 = 0x01;
    pub const HT: u32 = 0x02;
    pub const FF: u32 = 0x04;
    pub const ESC: u32 = 0x08;
    pub const DEL: u32 = 0x10;
    pub const C0: u32 = 0x20;
    pub const C1: u32 = 0x40;
}

/// flags from `'virtualedit'` (`OptVeFlags`).
///
/// Kept exactly as the original's own non-power-of-2, overlapping
/// values (`ALL`/`BLOCK`/`INSERT` are NOT independent bits: `ALL = 0x04`,
/// `BLOCK = 0x05`, `INSERT = 0x06` overlap bit `0x04`/`0x01`/`0x02`
/// respectively) - this is how upstream really defines them, not a
/// translation error.
pub mod opt_ve_flag {
    pub const ALL: u32 = 0x04;
    pub const BLOCK: u32 = 0x05;
    pub const INSERT: u32 = 0x06;
    pub const ONEMORE: u32 = 0x08;
    pub const NONE: u32 = 0x10;
    pub const NONE_U: u32 = 0x20;
}

/// flags from `'wildmode'` (`OptWimFlags`).
pub mod opt_wim_flag {
    pub const FULL: u32 = 0x01;
    pub const LONGEST: u32 = 0x02;
    pub const LIST: u32 = 0x04;
    pub const LASTUSED: u32 = 0x08;
    pub const NOSELECT: u32 = 0x10;
    pub const NOINSERT: u32 = 0x20;
}

/// flags from `'wildoptions'` (`OptWopFlags`).
pub mod opt_wop_flag {
    pub const FUZZY: u32 = 0x01;
    pub const TAGFILE: u32 = 0x02;
    pub const PUM: u32 = 0x04;
    pub const EXACTTEXT: u32 = 0x08;
}

// ============================================================
// Valid-string-value arrays (option_vars.generated.h). Translated
// directly as `&[&str]` slices - Rust slices know their own length, so
// the original's trailing `NULL` array terminator is dropped as
// redundant (same "drop the redundant C terminator/count" precedent
// used throughout this crate, e.g. `UEntry.ue_array`/`ue_size`).
// ============================================================

pub const OPT_AMBW_VALUES: &[&str] = &["single", "double"];
pub const OPT_BG_VALUES: &[&str] = &["light", "dark"];
pub const OPT_BS_VALUES: &[&str] = &["indent", "eol", "start", "nostop"];
pub const OPT_BKC_VALUES: &[&str] = &["yes", "auto", "no", "breaksymlink", "breakhardlink"];
pub const OPT_BO_VALUES: &[&str] = &[
    "all", "backspace", "cursor", "complete", "copy", "ctrlg", "error", "esc", "ex", "hangul",
    "insertmode", "lang", "mess", "showmatch", "operator", "register", "shell", "spell", "term",
    "wildmode",
];
pub const OPT_BRIOPT_VALUES: &[&str] = &["shift:", "min:", "sbr", "list:", "column:"];
pub const OPT_BH_VALUES: &[&str] = &["", "hide", "unload", "delete", "wipe"];
pub const OPT_BT_VALUES: &[&str] = &[
    "", "acwrite", "help", "nofile", "nowrite", "quickfix", "terminal", "prompt",
];
pub const OPT_CMP_VALUES: &[&str] = &["internal", "keepascii"];
pub const OPT_CB_VALUES: &[&str] = &["unnamed", "unnamedplus"];
pub const OPT_CPT_VALUES: &[&str] = &[
    ".", "w", "b", "u", "k", "kspell", "s", "i", "d", "]", "t", "U", "f", "F", "o",
];
pub const OPT_COT_VALUES: &[&str] = &[
    "fuzzy", "longest", "menu", "menuone", "nearest", "noinsert", "noselect", "nosort", "popup",
    "preinsert", "preselect", "preview",
];
pub const OPT_CSL_VALUES: &[&str] = &["", "slash", "backslash"];
pub const OPT_CULOPT_VALUES: &[&str] = &["line", "screenline", "number", "both"];
pub const OPT_DEBUG_VALUES: &[&str] = &["msg", "throw", "beep"];
pub const OPT_DIP_VALUES: &[&str] = &[
    "filler",
    "anchor",
    "context:",
    "iblank",
    "icase",
    "iwhite",
    "iwhiteall",
    "iwhiteeol",
    "horizontal",
    "vertical",
    "closeoff",
    "hiddenoff",
    "foldcolumn:",
    "followwrap",
    "internal",
    "indent-heuristic",
    "algorithm:",
    "inline:",
    "linematch:",
];
pub const OPT_DIP_ALGORITHM_VALUES: &[&str] = &["myers", "minimal", "patience", "histogram"];
pub const OPT_DIP_INLINE_VALUES: &[&str] = &["none", "simple", "char", "word"];
pub const OPT_DY_VALUES: &[&str] = &["lastline", "truncate", "uhex", "msgsep"];
pub const OPT_EAD_VALUES: &[&str] = &["both", "ver", "hor"];
pub const OPT_FF_VALUES: &[&str] = &["unix", "dos", "mac"];
pub const OPT_FCL_VALUES: &[&str] = &["all"];
pub const OPT_FDC_VALUES: &[&str] = &[
    "auto", "auto:1", "auto:2", "auto:3", "auto:4", "auto:5", "auto:6", "auto:7", "auto:8",
    "auto:9", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
];
pub const OPT_FDM_VALUES: &[&str] = &["manual", "expr", "marker", "indent", "syntax", "diff"];
pub const OPT_FDO_VALUES: &[&str] = &[
    "all", "block", "hor", "mark", "percent", "quickfix", "search", "tag", "insert", "undo",
    "jump",
];
pub const OPT_ICM_VALUES: &[&str] = &["nosplit", "split", ""];
pub const OPT_JOP_VALUES: &[&str] = &["stack", "view", "clean"];
pub const OPT_KM_VALUES: &[&str] = &["startsel", "stopsel"];
pub const OPT_LOP_VALUES: &[&str] = &["expr:0", "expr:1"];
pub const OPT_MOPT_VALUES: &[&str] = &["hit-enter", "wait:", "history:", "progress:"];
pub const OPT_MOUSEM_VALUES: &[&str] = &["extend", "popup", "popup_setpos"];
pub const OPT_MOUSESCROLL_VALUES: &[&str] = &["hor:", "ver:"];
pub const OPT_NF_VALUES: &[&str] = &["bin", "octal", "hex", "alpha", "unsigned", "blank"];
pub const OPT_PUMBORDER_VALUES: &[&str] = &[
    "", "double", "single", "shadow", "rounded", "solid", "bold", "none",
];
pub const OPT_RDB_VALUES: &[&str] = &["compositor", "nothrottle", "invalid", "nodelta", "line", "flush"];
pub const OPT_RLC_VALUES: &[&str] = &["search"];
pub const OPT_SBO_VALUES: &[&str] = &["ver", "hor", "jump"];
pub const OPT_SEL_VALUES: &[&str] = &["inclusive", "exclusive", "old"];
pub const OPT_SLM_VALUES: &[&str] = &["mouse", "key", "cmd"];
pub const OPT_SSOP_VALUES: &[&str] = &[
    "buffers", "winpos", "resize", "winsize", "localoptions", "options", "help", "blank",
    "globals", "slash", "unix", "sesdir", "curdir", "folds", "cursor", "tabpages", "terminal",
    "skiprtp",
];
pub const OPT_SLOC_VALUES: &[&str] = &["last", "statusline", "tabline"];
pub const OPT_SCL_VALUES: &[&str] = &[
    "yes", "no", "auto", "auto:1", "auto:2", "auto:3", "auto:4", "auto:5", "auto:6", "auto:7",
    "auto:8", "auto:9", "yes:1", "yes:2", "yes:3", "yes:4", "yes:5", "yes:6", "yes:7", "yes:8",
    "yes:9", "number",
];
pub const OPT_SPO_VALUES: &[&str] = &["camel", "noplainbuffer"];
pub const OPT_SPS_VALUES: &[&str] = &["best", "fast", "double", "expr:", "file:", "timeout:"];
pub const OPT_SPK_VALUES: &[&str] = &["cursor", "screen", "topline"];
pub const OPT_SWB_VALUES: &[&str] = &["useopen", "usetab", "split", "newtab", "vsplit", "uselast"];
pub const OPT_TCL_VALUES: &[&str] = &["left", "uselast"];
pub const OPT_TC_VALUES: &[&str] = &["followic", "ignore", "match", "followscs", "smart"];
pub const OPT_TPF_VALUES: &[&str] = &["BS", "HT", "FF", "ESC", "DEL", "C0", "C1"];
pub const OPT_VE_VALUES: &[&str] = &["block", "insert", "all", "onemore", "none", "NONE"];
pub const OPT_WIM_VALUES: &[&str] = &["full", "longest", "list", "lastused", "noselect", "noinsert"];
pub const OPT_WOP_VALUES: &[&str] = &["fuzzy", "tagfile", "pum", "exacttext"];
pub const OPT_WAK_VALUES: &[&str] = &["yes", "menu", "no"];
pub const OPT_WINBORDER_VALUES: &[&str] = &[
    "", "double", "single", "shadow", "rounded", "solid", "bold", "none",
];

// ============================================================
// The actual global option-value variables (`OptionVars`).
//
// One flat struct mirroring every one of the header's 336 `EXTERN`/
// `extern` option-value variables (excluding `empty_string_option`,
// translated separately above as a plain constant), in the same order,
// with the same terse `///< 'optionname'` comments as the original -
// see `globals.rs`'s own module doc comment for why this crate keeps
// this "one flat process-wide struct" architecture rather than
// splitting into per-subsystem globals or threading an explicit
// parameter through every future translated function.
// ============================================================

/// Every global-scope option value (`option_vars.h`'s `EXTERN`
/// variables).
pub struct OptionVars {
    pub p_ambw: Option<Vec<u8>>, // 'ambiwidth'
    pub p_acd: i32,              // 'autochdir'
    pub p_ai: i32,               // 'autoindent'
    pub p_bin: i32,              // 'binary'
    pub p_bomb: i32,             // 'bomb'
    pub p_bl: i32,               // 'buflisted'
    pub p_cin: i32,              // 'cindent'
    pub p_channel: OptInt,       // 'channel'
    pub p_cink: Option<Vec<u8>>, // 'cinkeys'
    pub p_cinsd: Option<Vec<u8>>, // 'cinscopedecls'
    pub p_cinw: Option<Vec<u8>>, // 'cinwords'
    pub p_cfu: Option<Vec<u8>>,  // 'completefunc'
    pub p_ofu: Option<Vec<u8>>,  // 'omnifunc'
    pub p_tsrfu: Option<Vec<u8>>, // 'thesaurusfunc'
    pub p_ci: i32,               // 'copyindent'
    pub p_ar: i32,               // 'autoread'
    pub p_aw: i32,               // 'autowrite'
    pub p_awa: i32,              // 'autowriteall'
    pub p_bs: Option<Vec<u8>>,   // 'backspace'
    pub p_bg: Option<Vec<u8>>,   // 'background'
    pub p_bk: i32,               // 'backup'
    pub p_bkc: Option<Vec<u8>>,  // 'backupcopy'
    pub bkc_flags: u32,          // flags from 'backupcopy'
    pub p_bdir: Option<Vec<u8>>, // 'backupdir'
    pub p_bex: Option<Vec<u8>>,  // 'backupext'
    pub p_bo: Option<Vec<u8>>,   // 'belloff'
    pub breakat_flags: [u8; 256], // which characters are in 'breakat'
    pub bo_flags: u32,
    pub p_bsk: Option<Vec<u8>>,  // 'backupskip'
    pub p_breakat: Option<Vec<u8>>, // 'breakat'
    pub p_bh: Option<Vec<u8>>,   // 'bufhidden'
    pub p_bt: Option<Vec<u8>>,   // 'buftype'
    pub p_busy: OptInt,          // 'busy'
    pub p_cmp: Option<Vec<u8>>,  // 'casemap'
    pub cmp_flags: u32,
    pub p_enc: Option<Vec<u8>>,  // 'encoding'
    pub p_deco: i32,             // 'delcombine'
    pub p_ccv: Option<Vec<u8>>,  // 'charconvert'
    pub p_cino: Option<Vec<u8>>, // 'cinoptions'
    pub p_cedit: Option<Vec<u8>>, // 'cedit'
    pub p_cb: Option<Vec<u8>>,   // 'clipboard'
    pub cb_flags: u32,
    pub p_cwh: OptInt,           // 'cmdwinheight'
    pub p_ch: OptInt,            // 'cmdheight'
    pub p_cms: Option<Vec<u8>>,  // 'commentstring'
    pub p_cpt: Option<Vec<u8>>,  // 'complete'
    pub p_cto: OptInt,           // 'completetimeout'
    pub p_columns: OptInt,       // 'columns'
    pub p_confirm: i32,          // 'confirm'
    pub p_cia: Option<Vec<u8>>,  // 'completeitemalign'
    pub cia_flags: u32,          // order flags of 'completeitemalign'
    pub p_cot: Option<Vec<u8>>,  // 'completeopt'
    pub cot_flags: u32,          // flags from 'completeopt'
    pub p_ac: i32,               // 'autocomplete'
    pub p_act: OptInt,           // 'autocompletetimeout'
    pub p_acl: OptInt,           // 'autocompletedelay'
    #[cfg(windows)]
    pub p_csl: Option<Vec<u8>>,  // 'completeslash' (BACKSLASH_IN_FILENAME-gated, see os/win_defs.rs)
    pub p_pumborder: Option<Vec<u8>>, // 'pumborder'
    pub p_pb: OptInt,            // 'pumblend'
    pub p_ph: OptInt,            // 'pumheight'
    pub p_pw: OptInt,            // 'pumwidth'
    pub p_pmw: OptInt,           // 'pummaxwidth'
    pub p_com: Option<Vec<u8>>,  // 'comments'
    pub p_cpo: Option<Vec<u8>>,  // 'cpoptions'
    pub p_debug: Option<Vec<u8>>, // 'debug'
    pub p_def: Option<Vec<u8>>,  // 'define'
    pub p_inc: Option<Vec<u8>>,  // 'include'
    pub p_dia: Option<Vec<u8>>,  // 'diffanchors'
    pub p_dip: Option<Vec<u8>>,  // 'diffopt'
    pub p_dex: Option<Vec<u8>>,  // 'diffexpr'
    pub p_dict: Option<Vec<u8>>, // 'dictionary'
    pub p_dg: i32,               // 'digraph'
    pub p_dir: Option<Vec<u8>>,  // 'directory'
    pub p_dy: Option<Vec<u8>>,   // 'display'
    pub dy_flags: u32,
    pub p_ead: Option<Vec<u8>>,  // 'eadirection'
    pub p_emoji: i32,            // 'emoji'
    pub p_ea: i32,               // 'equalalways'
    pub p_ep: Option<Vec<u8>>,   // 'equalprg'
    pub p_eb: i32,               // 'errorbells'
    pub p_ef: Option<Vec<u8>>,   // 'errorfile'
    pub p_efm: Option<Vec<u8>>,  // 'errorformat'
    pub p_gefm: Option<Vec<u8>>, // 'grepformat'
    pub p_gp: Option<Vec<u8>>,   // 'grepprg'
    pub p_eof: i32,              // 'endoffile'
    pub p_eol: i32,              // 'endofline'
    pub p_ei: Option<Vec<u8>>,   // 'eventignore'
    pub p_et: i32,               // 'expandtab'
    pub p_exrc: i32,             // 'exrc'
    pub p_fenc: Option<Vec<u8>>, // 'fileencoding'
    pub p_fencs: Option<Vec<u8>>, // 'fileencodings'
    pub p_ff: Option<Vec<u8>>,   // 'fileformat'
    pub p_ffs: Option<Vec<u8>>,  // 'fileformats'
    pub p_fic: i32,              // 'fileignorecase'
    pub p_ft: Option<Vec<u8>>,   // 'filetype'
    pub p_fcs: Option<Vec<u8>>,  // 'fillchar'
    pub p_ffu: Option<Vec<u8>>,  // 'findfunc'
    pub p_fixeol: i32,           // 'fixendofline'
    pub p_fcl: Option<Vec<u8>>,  // 'foldclose'
    pub p_fdls: OptInt,          // 'foldlevelstart'
    pub p_fdo: Option<Vec<u8>>,  // 'foldopen'
    pub fdo_flags: u32,
    pub p_fex: Option<Vec<u8>>,  // 'formatexpr'
    pub p_flp: Option<Vec<u8>>,  // 'formatlistpat'
    pub p_fo: Option<Vec<u8>>,   // 'formatoptions'
    pub p_fp: Option<Vec<u8>>,   // 'formatprg'
    pub p_fs: i32,               // 'fsync'
    pub p_gd: i32,               // 'gdefault'
    pub p_guicursor: Option<Vec<u8>>, // 'guicursor'
    pub p_guifont: Option<Vec<u8>>, // 'guifont'
    pub p_guifontwide: Option<Vec<u8>>, // 'guifontwide'
    pub p_hf: Option<Vec<u8>>,   // 'helpfile'
    pub p_hh: OptInt,            // 'helpheight'
    pub p_hlg: Option<Vec<u8>>,  // 'helplang'
    pub p_hid: i32,              // 'hidden'
    pub p_hl: Option<Vec<u8>>,   // 'highlight'
    pub p_hls: i32,              // 'hlsearch'
    pub p_hi: OptInt,            // 'history'
    pub p_arshape: i32,          // 'arabicshape'
    pub p_icon: i32,             // 'icon'
    pub p_iconstring: Option<Vec<u8>>, // 'iconstring'
    pub p_ic: i32,               // 'ignorecase'
    pub p_iminsert: OptInt,      // 'iminsert'
    pub p_imsearch: OptInt,      // 'imsearch'
    pub p_inf: i32,              // 'infercase'
    pub p_inex: Option<Vec<u8>>, // 'includeexpr'
    pub p_is: i32,               // 'incsearch'
    pub p_inde: Option<Vec<u8>>, // 'indentexpr'
    pub p_indk: Option<Vec<u8>>, // 'indentkeys'
    pub p_icm: Option<Vec<u8>>,  // 'inccommand'
    pub p_isf: Option<Vec<u8>>,  // 'isfname'
    pub p_isi: Option<Vec<u8>>,  // 'isident'
    pub p_isk: Option<Vec<u8>>,  // 'iskeyword'
    pub p_isp: Option<Vec<u8>>,  // 'isprint'
    pub p_js: i32,               // 'joinspaces'
    pub p_jop: Option<Vec<u8>>,  // 'jumpooptions'
    pub jop_flags: u32,
    pub p_keymap: Option<Vec<u8>>, // 'keymap'
    pub p_kp: Option<Vec<u8>>,   // 'keywordprg'
    pub p_km: Option<Vec<u8>>,   // 'keymodel'
    pub p_langmap: Option<Vec<u8>>, // 'langmap'
    pub p_lnr: i32,              // 'langnoremap'
    pub p_lrm: i32,              // 'langremap'
    pub p_lm: Option<Vec<u8>>,   // 'langmenu'
    pub p_lines: OptInt,         // 'lines'
    pub p_linespace: OptInt,     // 'linespace'
    pub p_lisp: i32,             // 'lisp'
    pub p_lop: Option<Vec<u8>>,  // 'lispoptions'
    pub p_lispwords: Option<Vec<u8>>, // 'lispwords'
    pub p_ls: OptInt,            // 'laststatus'
    pub p_stal: OptInt,          // 'showtabline'
    pub p_lcs: Option<Vec<u8>>,  // 'listchars'
    pub p_lz: i32,               // 'lazyredraw'
    pub p_lpl: i32,              // 'loadplugins'
    pub p_magic: i32,            // 'magic'
    pub p_menc: Option<Vec<u8>>, // 'makeencoding'
    pub p_mef: Option<Vec<u8>>,  // 'makeef'
    pub p_mp: Option<Vec<u8>>,   // 'makeprg'
    pub p_mps: Option<Vec<u8>>,  // 'matchpairs'
    pub p_mat: OptInt,           // 'matchtime'
    pub p_mco: OptInt,           // 'maxcombine'
    pub p_mfd: OptInt,           // 'maxfuncdepth'
    pub p_mmd: OptInt,           // 'maxmapdepth'
    pub p_mmp: OptInt,           // 'maxmempattern'
    pub p_mis: OptInt,           // 'menuitems'
    pub p_mopt: Option<Vec<u8>>, // 'messagesopt'
    pub p_msc: OptInt,           // 'maxsearchcount'
    pub p_msm: Option<Vec<u8>>,  // 'mkspellmem'
    pub p_ml: i32,               // 'modeline'
    pub p_mle: i32,              // 'modelineexpr'
    pub p_mls: OptInt,           // 'modelines'
    pub p_ma: i32,               // 'modifiable'
    pub p_mod: i32,              // 'modified'
    pub p_mouse: Option<Vec<u8>>, // 'mouse'
    pub p_mousem: Option<Vec<u8>>, // 'mousemodel'
    pub p_mousemev: i32,         // 'mousemoveevent'
    pub p_mousef: i32,           // 'mousefocus'
    pub p_mh: i32,               // 'mousehide'
    pub p_mousescroll: Option<Vec<u8>>, // 'mousescroll'
    pub p_mousescroll_vert: OptInt, // = MOUSESCROLL_VERT_DFLT
    pub p_mousescroll_hor: OptInt, // = MOUSESCROLL_HOR_DFLT
    pub p_mouset: OptInt,        // 'mousetime'
    pub p_more: i32,             // 'more'
    pub p_nf: Option<Vec<u8>>,   // 'nrformats'
    pub p_opfunc: Option<Vec<u8>>, // 'operatorfunc'
    pub p_para: Option<Vec<u8>>, // 'paragraphs'
    pub p_paste: i32,            // 'paste'
    pub p_pex: Option<Vec<u8>>,  // 'patchexpr'
    pub p_pm: Option<Vec<u8>>,   // 'patchmode'
    pub p_path: Option<Vec<u8>>, // 'path'
    pub p_cdpath: Option<Vec<u8>>, // 'cdpath'
    pub p_pi: i32,               // 'preserveindent'
    pub p_pyx: OptInt,           // 'pyxversion'
    pub p_qe: Option<Vec<u8>>,   // 'quoteescape'
    pub p_ro: i32,               // 'readonly'
    pub p_rdb: Option<Vec<u8>>,  // 'redrawdebug'
    pub rdb_flags: u32,
    pub p_rdt: OptInt,           // 'redrawtime'
    pub p_re: OptInt,            // 'regexpengine'
    pub p_report: OptInt,        // 'report'
    pub p_pvh: OptInt,           // 'previewheight'
    pub p_chi: OptInt,           // 'chistory'
    pub p_ari: i32,              // 'allowrevins'
    pub p_ri: i32,               // 'revins'
    pub p_ru: i32,               // 'ruler'
    pub p_ruf: Option<Vec<u8>>,  // 'rulerformat'
    pub p_plf: Option<Vec<u8>>,  // 'packlockfile'
    pub p_pp: Option<Vec<u8>>,   // 'packpath'
    pub p_qftf: Option<Vec<u8>>, // 'quickfixtextfunc'
    pub p_rtp: Option<Vec<u8>>,  // 'runtimepath'
    pub p_scbk: OptInt,          // 'scrollback'
    pub p_sj: OptInt,            // 'scrolljump'
    pub p_so: OptInt,            // 'scrolloff'
    pub p_sop: OptInt,           // 'scrolloffpad'
    pub p_sbo: Option<Vec<u8>>,  // 'scrollopt'
    pub p_sections: Option<Vec<u8>>, // 'sections'
    pub p_secure: i32,           // 'secure'
    pub p_sel: Option<Vec<u8>>,  // 'selection'
    pub p_slm: Option<Vec<u8>>,  // 'selectmode'
    pub p_ssop: Option<Vec<u8>>, // 'sessionoptions'
    pub ssop_flags: u32,
    pub p_sh: Option<Vec<u8>>,   // 'shell'
    pub p_shcf: Option<Vec<u8>>, // 'shellcmdflag'
    pub p_sp: Option<Vec<u8>>,   // 'shellpipe'
    pub p_shq: Option<Vec<u8>>,  // 'shellquote'
    pub p_sxq: Option<Vec<u8>>,  // 'shellxquote'
    pub p_sxe: Option<Vec<u8>>,  // 'shellxescape'
    pub p_srr: Option<Vec<u8>>,  // 'shellredir'
    pub p_stmp: i32,             // 'shelltemp'
    pub p_ssl: i32,              // 'shellslash'
    pub p_stl: Option<Vec<u8>>,  // 'statusline'
    pub p_wbr: Option<Vec<u8>>,  // 'winbar'
    pub p_sr: i32,               // 'shiftround'
    pub p_sw: OptInt,            // 'shiftwidth'
    pub p_shm: Option<Vec<u8>>,  // 'shortmess'
    pub p_sbr: Option<Vec<u8>>,  // 'showbreak'
    pub p_sc: i32,               // 'showcmd'
    pub p_sloc: Option<Vec<u8>>, // 'showcmdloc'
    pub p_sft: i32,              // 'showfulltag'
    pub p_sm: i32,               // 'showmatch'
    pub p_smd: i32,              // 'showmode'
    pub p_ss: OptInt,            // 'sidescroll'
    pub p_siso: OptInt,          // 'sidescrolloff'
    pub p_scs: i32,              // 'smartcase'
    pub p_si: i32,               // 'smartindent'
    pub p_sta: i32,              // 'smarttab'
    pub p_sts: OptInt,           // 'softtabstop'
    pub p_sb: i32,               // 'splitbelow'
    pub p_sua: Option<Vec<u8>>,  // 'suffixesadd'
    pub p_swf: i32,              // 'swapfile'
    pub p_smc: OptInt,           // 'synmaxcol'
    pub p_tpm: OptInt,           // 'tabpagemax'
    pub p_tal: Option<Vec<u8>>,  // 'tabline'
    pub p_tpf: Option<Vec<u8>>,  // 'termpastefilter'
    pub tpf_flags: u32,          // flags from 'termpastefilter'
    pub p_tfu: Option<Vec<u8>>,  // 'tagfunc'
    pub p_spc: Option<Vec<u8>>,  // 'spellcapcheck'
    pub p_spf: Option<Vec<u8>>,  // 'spellfile'
    pub p_spl: Option<Vec<u8>>,  // 'spelllang'
    pub p_spo: Option<Vec<u8>>,  // 'spelloptions'
    pub spo_flags: u32,
    pub p_sps: Option<Vec<u8>>,  // 'spellsuggest'
    pub p_spr: i32,              // 'splitright'
    pub p_sol: i32,              // 'startofline'
    pub p_su: Option<Vec<u8>>,   // 'suffixes'
    pub p_swb: Option<Vec<u8>>,  // 'switchbuf'
    pub swb_flags: u32,
    pub p_spk: Option<Vec<u8>>,  // 'splitkeep'
    pub p_syn: Option<Vec<u8>>,  // 'syntax'
    pub p_tcl: Option<Vec<u8>>,  // 'tabclose'
    pub tcl_flags: u32,          // flags from 'tabclose'
    pub p_ts: OptInt,            // 'tabstop'
    pub p_tbs: i32,              // 'tagbsearch'
    pub p_tc: Option<Vec<u8>>,   // 'tagcase'
    pub tc_flags: u32,           // flags from 'tagcase'
    pub p_tl: OptInt,            // 'taglength'
    pub p_tr: i32,               // 'tagrelative'
    pub p_tags: Option<Vec<u8>>, // 'tags'
    pub p_tgst: i32,             // 'tagstack'
    pub p_tbidi: i32,            // 'termbidi'
    pub p_tw: OptInt,            // 'textwidth'
    pub p_to: i32,               // 'tildeop'
    pub p_timeout: i32,          // 'timeout'
    pub p_tm: OptInt,            // 'timeoutlen'
    pub p_title: i32,            // 'title'
    pub p_titlelen: OptInt,      // 'titlelen'
    pub p_titleold: Option<Vec<u8>>, // 'titleold'
    pub p_titlestring: Option<Vec<u8>>, // 'titlestring'
    pub p_tsr: Option<Vec<u8>>,  // 'thesaurus'
    pub p_tgc: i32,              // 'termguicolors'
    pub p_ttimeout: i32,         // 'ttimeout'
    pub p_ttm: OptInt,           // 'ttimeoutlen'
    pub p_tf: i32,               // 'ttyfast'
    pub p_udir: Option<Vec<u8>>, // 'undodir'
    pub p_udf: i32,              // 'undofile'
    pub p_ul: OptInt,            // 'undolevels'
    pub p_ur: OptInt,            // 'undoreload'
    pub p_uc: OptInt,            // 'updatecount'
    pub p_ut: OptInt,            // 'updatetime'
    pub p_shada: Option<Vec<u8>>, // 'shada'
    pub p_shadafile: Option<Vec<u8>>, // 'shadafile'
    pub p_termsync: i32,         // 'termsync'
    pub p_vsts: Option<Vec<u8>>, // 'varsofttabstop'
    pub p_vts: Option<Vec<u8>>,  // 'vartabstop'
    pub p_vdir: Option<Vec<u8>>, // 'viewdir'
    pub p_vop: Option<Vec<u8>>,  // 'viewoptions'
    pub vop_flags: u32,          // uses OptSsopFlags
    pub p_vb: i32,               // 'visualbell'
    pub p_ve: Option<Vec<u8>>,   // 'virtualedit'
    pub ve_flags: u32,
    pub p_verbose: OptInt,       // 'verbose'
    pub p_vfile: Option<Vec<u8>>, // 'verbosefile'
    pub p_warn: i32,             // 'warn'
    pub p_wop: Option<Vec<u8>>,  // 'wildoptions'
    pub wop_flags: u32,
    pub p_window: OptInt,        // 'window'
    pub p_wak: Option<Vec<u8>>,  // 'winaltkeys'
    pub p_wig: Option<Vec<u8>>,  // 'wildignore'
    pub p_ww: Option<Vec<u8>>,   // 'whichwrap'
    pub p_wc: OptInt,            // 'wildchar'
    pub p_wcm: OptInt,           // 'wildcharm'
    pub p_wic: i32,              // 'wildignorecase'
    pub p_wim: Option<Vec<u8>>,  // 'wildmode'
    pub p_wmnu: i32,             // 'wildmenu'
    pub p_winborder: Option<Vec<u8>>, // 'winborder'
    pub p_wh: OptInt,            // 'winheight'
    pub p_wmh: OptInt,           // 'winminheight'
    pub p_wmw: OptInt,           // 'winminwidth'
    pub p_wiw: OptInt,           // 'winwidth'
    pub p_wm: OptInt,            // 'wrapmargin'
    pub p_ws: i32,               // 'wrapscan'
    pub p_write: i32,            // 'write'
    pub p_wa: i32,               // 'writeany'
    pub p_wb: i32,               // 'writebackup'
    pub p_wd: OptInt,            // 'writedelay'
    pub p_cdh: i32,              // 'cdhome'
}

impl Default for OptionVars {
    /// A purely mechanical, structural default (every field zero/empty/
    /// null) - **not** a translation of `option.c`'s real startup
    /// defaults table (`options.lua`'s per-option `default` fields).
    /// Same caveat as `BufT`/`WinT`/`Globals`'s own `Default` impls:
    /// reflecting a few individually-recalled "realistic" option
    /// defaults here while leaving the rest at 0 would misleadingly
    /// suggest more fidelity than this impl actually has.
    fn default() -> Self {
        OptionVars {
            p_ambw: None,
            p_acd: 0,
            p_ai: 0,
            p_bin: 0,
            p_bomb: 0,
            p_bl: 0,
            p_cin: 0,
            p_channel: 0,
            p_cink: None,
            p_cinsd: None,
            p_cinw: None,
            p_cfu: None,
            p_ofu: None,
            p_tsrfu: None,
            p_ci: 0,
            p_ar: 0,
            p_aw: 0,
            p_awa: 0,
            p_bs: None,
            p_bg: None,
            p_bk: 0,
            p_bkc: None,
            bkc_flags: 0,
            p_bdir: None,
            p_bex: None,
            p_bo: None,
            breakat_flags: [0; 256],
            bo_flags: 0,
            p_bsk: None,
            p_breakat: None,
            p_bh: None,
            p_bt: None,
            p_busy: 0,
            p_cmp: None,
            cmp_flags: 0,
            p_enc: None,
            p_deco: 0,
            p_ccv: None,
            p_cino: None,
            p_cedit: None,
            p_cb: None,
            cb_flags: 0,
            p_cwh: 0,
            p_ch: 0,
            p_cms: None,
            p_cpt: None,
            p_cto: 0,
            p_columns: 0,
            p_confirm: 0,
            p_cia: None,
            cia_flags: 0,
            p_cot: None,
            cot_flags: 0,
            p_ac: 0,
            p_act: 0,
            p_acl: 0,
            #[cfg(windows)]
            p_csl: None,
            p_pumborder: None,
            p_pb: 0,
            p_ph: 0,
            p_pw: 0,
            p_pmw: 0,
            p_com: None,
            p_cpo: None,
            p_debug: None,
            p_def: None,
            p_inc: None,
            p_dia: None,
            p_dip: None,
            p_dex: None,
            p_dict: None,
            p_dg: 0,
            p_dir: None,
            p_dy: None,
            dy_flags: 0,
            p_ead: None,
            p_emoji: 0,
            p_ea: 0,
            p_ep: None,
            p_eb: 0,
            p_ef: None,
            p_efm: None,
            p_gefm: None,
            p_gp: None,
            p_eof: 0,
            p_eol: 0,
            p_ei: None,
            p_et: 0,
            p_exrc: 0,
            p_fenc: None,
            p_fencs: None,
            p_ff: None,
            p_ffs: None,
            p_fic: 0,
            p_ft: None,
            p_fcs: None,
            p_ffu: None,
            p_fixeol: 0,
            p_fcl: None,
            p_fdls: 0,
            p_fdo: None,
            fdo_flags: 0,
            p_fex: None,
            p_flp: None,
            p_fo: None,
            p_fp: None,
            p_fs: 0,
            p_gd: 0,
            p_guicursor: None,
            p_guifont: None,
            p_guifontwide: None,
            p_hf: None,
            p_hh: 0,
            p_hlg: None,
            p_hid: 0,
            p_hl: None,
            p_hls: 0,
            p_hi: 0,
            p_arshape: 0,
            p_icon: 0,
            p_iconstring: None,
            p_ic: 0,
            p_iminsert: 0,
            p_imsearch: 0,
            p_inf: 0,
            p_inex: None,
            p_is: 0,
            p_inde: None,
            p_indk: None,
            p_icm: None,
            p_isf: None,
            p_isi: None,
            p_isk: None,
            p_isp: None,
            p_js: 0,
            p_jop: None,
            jop_flags: 0,
            p_keymap: None,
            p_kp: None,
            p_km: None,
            p_langmap: None,
            p_lnr: 0,
            p_lrm: 0,
            p_lm: None,
            p_lines: 0,
            p_linespace: 0,
            p_lisp: 0,
            p_lop: None,
            p_lispwords: None,
            p_ls: 0,
            p_stal: 0,
            p_lcs: None,
            p_lz: 0,
            p_lpl: 0,
            p_magic: 0,
            p_menc: None,
            p_mef: None,
            p_mp: None,
            p_mps: None,
            p_mat: 0,
            p_mco: 0,
            p_mfd: 0,
            p_mmd: 0,
            p_mmp: 0,
            p_mis: 0,
            p_mopt: None,
            p_msc: 0,
            p_msm: None,
            p_ml: 0,
            p_mle: 0,
            p_mls: 0,
            p_ma: 0,
            p_mod: 0,
            p_mouse: None,
            p_mousem: None,
            p_mousemev: 0,
            p_mousef: 0,
            p_mh: 0,
            p_mousescroll: None,
            p_mousescroll_vert: MOUSESCROLL_VERT_DFLT,
            p_mousescroll_hor: MOUSESCROLL_HOR_DFLT,
            p_mouset: 0,
            p_more: 0,
            p_nf: None,
            p_opfunc: None,
            p_para: None,
            p_paste: 0,
            p_pex: None,
            p_pm: None,
            p_path: None,
            p_cdpath: None,
            p_pi: 0,
            p_pyx: 0,
            p_qe: None,
            p_ro: 0,
            p_rdb: None,
            rdb_flags: 0,
            p_rdt: 0,
            p_re: 0,
            p_report: 0,
            p_pvh: 0,
            p_chi: 0,
            p_ari: 0,
            p_ri: 0,
            p_ru: 0,
            p_ruf: None,
            p_plf: None,
            p_pp: None,
            p_qftf: None,
            p_rtp: None,
            p_scbk: 0,
            p_sj: 0,
            p_so: 0,
            p_sop: 0,
            p_sbo: None,
            p_sections: None,
            p_secure: 0,
            p_sel: None,
            p_slm: None,
            p_ssop: None,
            ssop_flags: 0,
            p_sh: None,
            p_shcf: None,
            p_sp: None,
            p_shq: None,
            p_sxq: None,
            p_sxe: None,
            p_srr: None,
            p_stmp: 0,
            p_ssl: 0,
            p_stl: None,
            p_wbr: None,
            p_sr: 0,
            p_sw: 0,
            p_shm: None,
            p_sbr: None,
            p_sc: 0,
            p_sloc: None,
            p_sft: 0,
            p_sm: 0,
            p_smd: 0,
            p_ss: 0,
            p_siso: 0,
            p_scs: 0,
            p_si: 0,
            p_sta: 0,
            p_sts: 0,
            p_sb: 0,
            p_sua: None,
            p_swf: 0,
            p_smc: 0,
            p_tpm: 0,
            p_tal: None,
            p_tpf: None,
            tpf_flags: 0,
            p_tfu: None,
            p_spc: None,
            p_spf: None,
            p_spl: None,
            p_spo: None,
            spo_flags: 0,
            p_sps: None,
            p_spr: 0,
            p_sol: 0,
            p_su: None,
            p_swb: None,
            swb_flags: 0,
            p_spk: None,
            p_syn: None,
            p_tcl: None,
            tcl_flags: 0,
            p_ts: 0,
            p_tbs: 0,
            p_tc: None,
            tc_flags: 0,
            p_tl: 0,
            p_tr: 0,
            p_tags: None,
            p_tgst: 0,
            p_tbidi: 0,
            p_tw: 0,
            p_to: 0,
            p_timeout: 0,
            p_tm: 0,
            p_title: 0,
            p_titlelen: 0,
            p_titleold: None,
            p_titlestring: None,
            p_tsr: None,
            p_tgc: 0,
            p_ttimeout: 0,
            p_ttm: 0,
            p_tf: 0,
            p_udir: None,
            p_udf: 0,
            p_ul: 0,
            p_ur: 0,
            p_uc: 0,
            p_ut: 0,
            p_shada: None,
            p_shadafile: None,
            p_termsync: 0,
            p_vsts: None,
            p_vts: None,
            p_vdir: None,
            p_vop: None,
            vop_flags: 0,
            p_vb: 0,
            p_ve: None,
            ve_flags: 0,
            p_verbose: 0,
            p_vfile: None,
            p_warn: 0,
            p_wop: None,
            wop_flags: 0,
            p_window: 0,
            p_wak: None,
            p_wig: None,
            p_ww: None,
            p_wc: 0,
            p_wcm: 0,
            p_wic: 0,
            p_wim: None,
            p_wmnu: 0,
            p_winborder: None,
            p_wh: 0,
            p_wmh: 0,
            p_wmw: 0,
            p_wiw: 0,
            p_wm: 0,
            p_ws: 0,
            p_write: 0,
            p_wa: 0,
            p_wb: 0,
            p_wd: 0,
            p_cdh: 0,
        }
    }
}

/// The single, global, mutable option-value state instance - the Rust
/// equivalent of `option_vars.h`'s `EXTERN` mechanism, following exactly
/// the same pattern as `crate::globals::GLOBALS` (see that static's own
/// doc comment for the full reasoning: preserves the original's
/// implicit, no-parameter global access at every call site via
/// `crate::globals::GlobalCell`, rather than a bare `static mut`
/// reference or a `Mutex`/`RefCell` that could newly panic/deadlock on
/// reentrant access the original never worried about).
pub static OPTION_VARS: std::sync::LazyLock<crate::globals::GlobalCell<OptionVars>> =
    std::sync::LazyLock::new(|| crate::globals::GlobalCell::new(OptionVars::default()));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fo_all_combines_expected_flags() {
        assert_eq!(FO_ALL, "tcro/q2vlb1mMBn,aw]jp");
    }

    #[test]
    fn cpo_vim_and_vi_defaults_are_distinct() {
        assert_ne!(CPO_VIM, CPO_VI);
    }

    #[test]
    fn shm_all_abbreviations_matches_c_macro() {
        assert_eq!(SHM_ALL_ABBREVIATIONS, [b'r', b'm', b'l', b'w']);
    }

    #[test]
    fn max_stcwidth_matches_c_macro_expansion() {
        // MAX_NUMBERWIDTH + SIGN_SHOW_MAX * SIGN_WIDTH + 9 = 20 + 9*2 + 9
        assert_eq!(MAX_STCWIDTH, 20 + 9 * 2 + 9);
    }

    #[test]
    fn eol_constants_match_c_macros() {
        assert_eq!(EOL_UNKNOWN, -1);
        assert_eq!(EOL_UNIX, 0);
        assert_eq!(EOL_DOS, 1);
        assert_eq!(EOL_MAC, 2);
    }

    #[test]
    fn scl_constants_match_c_macros() {
        assert_eq!(SCL_NO, -1);
        assert_eq!(SCL_NUM, -2);
    }

    #[test]
    fn opt_bkc_flag_bits_are_distinct() {
        let all = [
            opt_bkc_flag::YES,
            opt_bkc_flag::AUTO,
            opt_bkc_flag::NO,
            opt_bkc_flag::BREAKSYMLINK,
            opt_bkc_flag::BREAKHARDLINK,
        ];
        let mut seen = 0;
        for f in all {
            assert_eq!(seen & f, 0);
            seen |= f;
        }
    }

    #[test]
    fn opt_ve_flag_matches_upstream_overlapping_values() {
        // Deliberately overlapping, verified against option_vars.generated.h.
        assert_eq!(opt_ve_flag::ALL, 0x04);
        assert_eq!(opt_ve_flag::BLOCK, 0x05);
        assert_eq!(opt_ve_flag::INSERT, 0x06);
    }

    #[test]
    fn value_arrays_have_expected_lengths() {
        assert_eq!(OPT_AMBW_VALUES.len(), 2);
        assert_eq!(OPT_BO_VALUES.len(), 20);
        assert_eq!(OPT_SCL_VALUES.len(), 22);
        assert_eq!(OPT_SSOP_VALUES.len(), 18);
    }

    #[test]
    fn empty_string_option_is_empty() {
        assert_eq!(EMPTY_STRING_OPTION, b"");
    }

    #[test]
    fn no_local_undolevel_matches_c_macro() {
        assert_eq!(NO_LOCAL_UNDOLEVEL, -123_456);
    }
}
